const ACTION_TYPES = {
  TYPE_SEARCH: "TYPE_SEARCH",
  SUBMIT_SEARCH: "SUBMIT_SEARCH",
  FETCH_DATA: "FETCH_DATA",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
};

export default ACTION_TYPES;
